version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:bionic
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: |
            apt update
